mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: ['orders', 'http://localhost:8000/api/orders/{id}']
                subscribe: ['orders', 'http://localhost:8000/api/orders/{id}']
